name: Pelican publish and Google Cloud App Engine deploy

on:
  push:
    branches:
      - main

jobs:

  production-publish:
    if: github.repository == 'PJECZ/pjecz-andromeda-pelican'
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build web site
        run: |
          pelican content -o output -s publishconf.py
      - name: Authenticate
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to App Engine
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: "app.yaml"
          working_directory: "."
          promote: true
